### ISSUE TITLE
Blueprint should migrate to the latest version of JHipster

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-migrate#4]
If I try this blueprint on my [jhipster8-demo](https://github.com/mraible/jhipster8-demo) project, it only updates it to v8.0.0 instead of the latest v8.2.1. Since I use dependabot to update dependencies, it downgrades dependencies rather than upgrading them.

<img width="2234" alt="Screenshot 2024-03-20 at 12 14 04 PM" src="https://github.com/jhipster/generator-jhipster-migrate/assets/17892/8c72fdb9-49a9-48ba-abb8-91b193b143c7">

**Comment by mshima** [comment]
by default it will upgrade to the dependent version.

**Comment by mraible** [comment]
Can you please upgrade this blueprint to 8.2.1 and do a new release?

**Comment by mshima** [comment]
Done.
